version: '3.3'
services:
  frontend:
    container_name: IPC-Slave-Frontend
    image: fan9704/iptable_controller_frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_APP_TITLE=IPtable-Controller-Frontend
    environment:
      - VITE_HOST_IP=${VITE_HOST_IP}
      - VITE_APP_TITLE=IPtable-Controller-Frontend
    ports:
      - "80:80"
